# https://www.getzola.org/documentation/getting-started/configuration/
base_url = "https://gaelreyrol.dev"

title = "Gaël Reyrol"
description = "Je suis développeur autodidacte, passionné de web principalement"

default_language = "fr"

[markdown]
highlight_code = true
highlight_theme = "solarized-light"
render_emoji = true

[extra]